
DefaultProxyGroup:
  DIRECT:
    RuleProviders:
      - ğŸ  LocalAreaNetwork: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml'
        ğŸ  DirectCustom: 'https://raw.githubusercontent.com/LeiShi1313/ss-to-clash/master/Custom/Direct.yaml'
  Reject:
    RuleProviders:
      - ğŸˆ²ï¸ BanAD: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml'
      # - ğŸˆ²ï¸ BanEasyList: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml'
      # - ğŸˆ²ï¸ BanEasyListChina: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml'
      # - ğŸˆ²ï¸ BanProgramAD: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml'
      # - ğŸˆ²ï¸ BanCustom: 'https://raw.githubusercontent.com/LeiShi1313/ss-to-clash/master/Custom/Ban.yaml'
  China:
    RuleProviders:
      # - ğŸ€„ï¸ ChinaDomain: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml'
      # - ğŸ€„ï¸ ChinaCompanyIp: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml'
      - ğŸ€„ï¸ ChinaIp: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml'
        ğŸ€„ï¸ ChinaCustom: 'https://raw.githubusercontent.com/LeiShi1313/ss-to-clash/master/Custom/China.yaml'
  Proxy:
    RuleProviders:
      - âœˆï¸ ProxyLite: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyLite.yaml'
        âœˆï¸ ProxyGFWList: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyGFWlist.yaml'
        âœˆï¸ï¸ ProxyMedia: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml'
      # - âœˆï¸ ProxyCustom: 'https://raw.githubusercontent.com/LeiShi1313/ss-to-clash/master/Custom/Proxy.yaml',

CustomProxyGroup:
  SpeedTest:
    CustomRules:
      - DOMAIN-KEYWORD,speedtest

  BiliBili:
    CustomRules:
      - DOMAIN-KEYWORD,bilibili
    RuleProviders:
      - BiliBili: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml
